apiVersion: v1
kind: Config
clusters:
  - name: webhook
    cluster:
      server: http://dev:35123/auth/kube
      insecure-skip-tls-verify: true

users:
  - name: webhook

current-context: webhook
contexts:
  - name: webhook
    context:
      cluster: webhook
      user: webhook
