// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: khepri/horus/extend.proto

package horus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khepri_horus_extend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_khepri_horus_extend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_khepri_horus_extend_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptInvitationRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Token *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are assignable to Key:
	//
	//	*ListAccountRequest_Mine
	//	*ListAccountRequest_SiloId
	//	*ListAccountRequest_SiloAlias
	Key isListAccountRequest_Key `protobuf_oneof:"key"`
}

func (x *ListAccountRequest) Reset() {
	*x = ListAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khepri_horus_extend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountRequest) ProtoMessage() {}

func (x *ListAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_khepri_horus_extend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountRequest.ProtoReflect.Descriptor instead.
func (*ListAccountRequest) Descriptor() ([]byte, []int) {
	return file_khepri_horus_extend_proto_rawDescGZIP(), []int{1}
}

func (x *ListAccountRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAccountRequest) GetToken() *timestamppb.Timestamp {
	if x != nil {
		return x.Token
	}
	return nil
}

func (m *ListAccountRequest) GetKey() isListAccountRequest_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (x *ListAccountRequest) GetMine() *emptypb.Empty {
	if x, ok := x.GetKey().(*ListAccountRequest_Mine); ok {
		return x.Mine
	}
	return nil
}

func (x *ListAccountRequest) GetSiloId() []byte {
	if x, ok := x.GetKey().(*ListAccountRequest_SiloId); ok {
		return x.SiloId
	}
	return nil
}

func (x *ListAccountRequest) GetSiloAlias() string {
	if x, ok := x.GetKey().(*ListAccountRequest_SiloAlias); ok {
		return x.SiloAlias
	}
	return ""
}

type isListAccountRequest_Key interface {
	isListAccountRequest_Key()
}

type ListAccountRequest_Mine struct {
	Mine *emptypb.Empty `protobuf:"bytes,3,opt,name=mine,proto3,oneof"`
}

type ListAccountRequest_SiloId struct {
	SiloId []byte `protobuf:"bytes,4,opt,name=silo_id,json=siloId,proto3,oneof"`
}

type ListAccountRequest_SiloAlias struct {
	SiloAlias string `protobuf:"bytes,5,opt,name=silo_alias,json=siloAlias,proto3,oneof"`
}

func (*ListAccountRequest_Mine) isListAccountRequest_Key() {}

func (*ListAccountRequest_SiloId) isListAccountRequest_Key() {}

func (*ListAccountRequest_SiloAlias) isListAccountRequest_Key() {}

type ListAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Account `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListAccountResponse) Reset() {
	*x = ListAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khepri_horus_extend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountResponse) ProtoMessage() {}

func (x *ListAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_khepri_horus_extend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountResponse.ProtoReflect.Descriptor instead.
func (*ListAccountResponse) Descriptor() ([]byte, []int) {
	return file_khepri_horus_extend_proto_rawDescGZIP(), []int{2}
}

func (x *ListAccountResponse) GetItems() []*Account {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_khepri_horus_extend_proto protoreflect.FileDescriptor

var file_khepri_horus_extend_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6b, 0x68, 0x65, 0x70, 0x72, 0x69, 0x2f, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6b, 0x68, 0x65,
	0x70, 0x72, 0x69, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6b, 0x68, 0x65, 0x70, 0x72, 0x69, 0x2f,
	0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x29, 0x0a, 0x17, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0xcd, 0x01,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x04,
	0x6d, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x73, 0x69,
	0x6c, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x69, 0x6c, 0x6f, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x69, 0x6c, 0x6f, 0x5f, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x73, 0x69, 0x6c,
	0x6f, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x42, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x68, 0x65, 0x70, 0x72, 0x69, 0x2e, 0x68, 0x6f, 0x72,
	0x75, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x42, 0x12, 0x5a, 0x10, 0x6b, 0x68, 0x65, 0x70, 0x72, 0x69, 0x2e, 0x64, 0x65, 0x76, 0x2f,
	0x68, 0x6f, 0x72, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_khepri_horus_extend_proto_rawDescOnce sync.Once
	file_khepri_horus_extend_proto_rawDescData = file_khepri_horus_extend_proto_rawDesc
)

func file_khepri_horus_extend_proto_rawDescGZIP() []byte {
	file_khepri_horus_extend_proto_rawDescOnce.Do(func() {
		file_khepri_horus_extend_proto_rawDescData = protoimpl.X.CompressGZIP(file_khepri_horus_extend_proto_rawDescData)
	})
	return file_khepri_horus_extend_proto_rawDescData
}

var file_khepri_horus_extend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_khepri_horus_extend_proto_goTypes = []interface{}{
	(*AcceptInvitationRequest)(nil), // 0: khepri.horus.AcceptInvitationRequest
	(*ListAccountRequest)(nil),      // 1: khepri.horus.ListAccountRequest
	(*ListAccountResponse)(nil),     // 2: khepri.horus.ListAccountResponse
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 4: google.protobuf.Empty
	(*Account)(nil),                 // 5: khepri.horus.Account
}
var file_khepri_horus_extend_proto_depIdxs = []int32{
	3, // 0: khepri.horus.ListAccountRequest.token:type_name -> google.protobuf.Timestamp
	4, // 1: khepri.horus.ListAccountRequest.mine:type_name -> google.protobuf.Empty
	5, // 2: khepri.horus.ListAccountResponse.items:type_name -> khepri.horus.Account
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_khepri_horus_extend_proto_init() }
func file_khepri_horus_extend_proto_init() {
	if File_khepri_horus_extend_proto != nil {
		return
	}
	file_khepri_horus_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_khepri_horus_extend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptInvitationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khepri_horus_extend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khepri_horus_extend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_khepri_horus_extend_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ListAccountRequest_Mine)(nil),
		(*ListAccountRequest_SiloId)(nil),
		(*ListAccountRequest_SiloAlias)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_khepri_horus_extend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_khepri_horus_extend_proto_goTypes,
		DependencyIndexes: file_khepri_horus_extend_proto_depIdxs,
		MessageInfos:      file_khepri_horus_extend_proto_msgTypes,
	}.Build()
	File_khepri_horus_extend_proto = out.File
	file_khepri_horus_extend_proto_rawDesc = nil
	file_khepri_horus_extend_proto_goTypes = nil
	file_khepri_horus_extend_proto_depIdxs = nil
}
