// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"khepri.dev/horus/store/ent/authorizer"
	"khepri.dev/horus/store/ent/predicate"
)

// AuthorizerDelete is the builder for deleting a Authorizer entity.
type AuthorizerDelete struct {
	config
	hooks    []Hook
	mutation *AuthorizerMutation
}

// Where appends a list predicates to the AuthorizerDelete builder.
func (ad *AuthorizerDelete) Where(ps ...predicate.Authorizer) *AuthorizerDelete {
	ad.mutation.Where(ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *AuthorizerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ad.sqlExec, ad.mutation, ad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *AuthorizerDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *AuthorizerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authorizer.Table, sqlgraph.NewFieldSpec(authorizer.FieldID, field.TypeInt))
	if ps := ad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ad.mutation.done = true
	return affected, err
}

// AuthorizerDeleteOne is the builder for deleting a single Authorizer entity.
type AuthorizerDeleteOne struct {
	ad *AuthorizerDelete
}

// Where appends a list predicates to the AuthorizerDelete builder.
func (ado *AuthorizerDeleteOne) Where(ps ...predicate.Authorizer) *AuthorizerDeleteOne {
	ado.ad.mutation.Where(ps...)
	return ado
}

// Exec executes the deletion query.
func (ado *AuthorizerDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authorizer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *AuthorizerDeleteOne) ExecX(ctx context.Context) {
	if err := ado.Exec(ctx); err != nil {
		panic(err)
	}
}
