services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    command: [ "sh", "-c", "while sleep 1000; do :; done" ]

    privileged: true

    volumes:
      - type: bind
        source: ..
        target: /workspaces/horus

      - type: bind
        source: ${HOME}/workspace
        target: /workspace
      - type: bind
        source: ./k3s/
        target: /etc/rancher/k3s/

    expose:
      - 35122
      - 35123

  gw:
    image: envoyproxy/envoy:v1.30-latest

    ports:
      - target: 9901
        published: 9901
      - target: 35121
        published: 35121

    volumes:
      - type: bind
        source: ./envoy.yaml
        target: /etc/envoy/envoy.yaml
        read_only: true

  docker:
    image: library/docker:26-dind
    command: 
      - --tlsverify=false
      - --insecure-registry=registry:5000

    privileged: true

  registry:
    image: library/registry:2.8.3

  k3s:
    image: rancher/k3s:v1.30.0-k3s1
    command:
      - server
      - --tls-san-security=false
    
    privileged: true

    volumes:
      - type: bind
        source: ./k3s/
        target: /etc/rancher/k3s/
