// Code generated by "protoc-gen-entpb". DO NOT EDIT

package bare

import (
	context "context"
	uuid "github.com/google/uuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	horus "khepri.dev/horus"
	ent "khepri.dev/horus/ent"
	predicate "khepri.dev/horus/ent/predicate"
	silo "khepri.dev/horus/ent/silo"
)

type SiloServiceServer struct {
	db *ent.Client
	horus.UnimplementedSiloServiceServer
}

func NewSiloServiceServer(db *ent.Client) *SiloServiceServer {
	return &SiloServiceServer{db: db}
}
func (s *SiloServiceServer) Create(ctx context.Context, req *horus.CreateSiloRequest) (*horus.Silo, error) {
	q := s.db.Silo.Create()
	if v := req.Alias; v != nil {
		q.SetAlias(*v)
	}
	if v := req.Name; v != nil {
		q.SetName(*v)
	}
	if v := req.Description; v != nil {
		q.SetDescription(*v)
	}

	res, err := q.Save(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoSilo(res), nil
}
func (s *SiloServiceServer) Delete(ctx context.Context, req *horus.DeleteSiloRequest) (*emptypb.Empty, error) {
	q := s.db.Silo.Delete()
	switch t := req.GetKey().(type) {
	case *horus.DeleteSiloRequest_Id:
		if v, err := uuid.FromBytes(t.Id); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			q.Where(silo.IDEQ(v))
		}
	case *horus.DeleteSiloRequest_Alias:
		q.Where(silo.AliasEQ(t.Alias))
	default:
		return nil, status.Errorf(codes.InvalidArgument, "key not provided")
	}

	_, err := q.Exec(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return &emptypb.Empty{}, nil
}
func (s *SiloServiceServer) Get(ctx context.Context, req *horus.GetSiloRequest) (*horus.Silo, error) {
	q := s.db.Silo.Query()
	if p, err := GetSiloSpecifier(req); err != nil {
		return nil, err
	} else {
		q.Where(p)
	}

	res, err := q.Only(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoSilo(res), nil
}
func (s *SiloServiceServer) Update(ctx context.Context, req *horus.UpdateSiloRequest) (*horus.Silo, error) {
	id, err := uuid.FromBytes(req.GetId())
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
	}

	q := s.db.Silo.UpdateOneID(id)
	if v := req.Alias; v != nil {
		q.SetAlias(*v)
	}
	if v := req.Name; v != nil {
		q.SetName(*v)
	}
	if v := req.Description; v != nil {
		q.SetDescription(*v)
	}

	res, err := q.Save(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoSilo(res), nil
}
func ToProtoSilo(v *ent.Silo) *horus.Silo {
	m := &horus.Silo{}
	m.Id = v.ID[:]
	m.DateCreated = timestamppb.New(v.DateCreated)
	m.Alias = v.Alias
	m.Name = v.Name
	m.Description = v.Description
	return m
}
func GetSiloId(ctx context.Context, db *ent.Client, req *horus.GetSiloRequest) (uuid.UUID, error) {
	var r uuid.UUID
	k := req.GetKey()
	if t, ok := k.(*horus.GetSiloRequest_Id); ok {
		if v, err := uuid.FromBytes(t.Id); err != nil {
			return r, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	q := db.Silo.Query()
	switch t := k.(type) {
	case *horus.GetSiloRequest_Alias:
		q.Where(silo.AliasEQ(t.Alias))
	case nil:
		return r, status.Errorf(codes.InvalidArgument, "key not provided")
	default:
		return r, status.Errorf(codes.Unimplemented, "unknown type of key")
	}
	if v, err := q.OnlyID(ctx); err != nil {
		return r, ToStatus(err)
	} else {
		return v, nil
	}
}
func GetSiloSpecifier(req *horus.GetSiloRequest) (predicate.Silo, error) {
	switch t := req.GetKey().(type) {
	case *horus.GetSiloRequest_Id:
		if v, err := uuid.FromBytes(t.Id); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return silo.IDEQ(v), nil
		}
	case *horus.GetSiloRequest_Alias:
		return silo.AliasEQ(t.Alias), nil
	case nil:
		return nil, status.Errorf(codes.InvalidArgument, "key not provided")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key")
	}
}
