// Code generated by "protoc-gen-entpb". DO NOT EDIT

package bare

import (
	context "context"
	uuid "github.com/google/uuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	horus "khepri.dev/horus"
	ent "khepri.dev/horus/ent"
	account "khepri.dev/horus/ent/account"
	identity "khepri.dev/horus/ent/identity"
	predicate "khepri.dev/horus/ent/predicate"
	user "khepri.dev/horus/ent/user"
)

type UserServiceServer struct {
	db *ent.Client
	horus.UnimplementedUserServiceServer
}

func NewUserServiceServer(db *ent.Client) *UserServiceServer {
	return &UserServiceServer{db: db}
}
func (s *UserServiceServer) Create(ctx context.Context, req *horus.CreateUserRequest) (*horus.User, error) {
	q := s.db.User.Create()
	if v := req.Alias; v != nil {
		q.SetAlias(*v)
	}
	if v := req.GetParent(); v != nil {
		if id, err := GetUserId(ctx, s.db, v); err != nil {
			return nil, err
		} else {
			q.SetParentID(id)
		}
	}

	res, err := q.Save(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoUser(res), nil
}
func (s *UserServiceServer) Delete(ctx context.Context, req *horus.GetUserRequest) (*emptypb.Empty, error) {
	q := s.db.User.Delete()
	switch t := req.GetKey().(type) {
	case *horus.GetUserRequest_Id:
		if v, err := uuid.FromBytes(t.Id); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			q.Where(user.IDEQ(v))
		}
	case *horus.GetUserRequest_Alias:
		q.Where(user.AliasEQ(t.Alias))
	default:
		return nil, status.Errorf(codes.InvalidArgument, "key not provided")
	}

	_, err := q.Exec(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return &emptypb.Empty{}, nil
}
func (s *UserServiceServer) Get(ctx context.Context, req *horus.GetUserRequest) (*horus.User, error) {
	q := s.db.User.Query()
	if p, err := GetUserSpecifier(req); err != nil {
		return nil, err
	} else {
		q.Where(p)
	}

	q.WithParent(func(q *ent.UserQuery) { q.Select(user.FieldID) })
	q.WithIdentities(func(q *ent.IdentityQuery) { q.Select(identity.FieldID) })
	q.WithAccounts(func(q *ent.AccountQuery) { q.Select(account.FieldID) })
	q.WithChildren(func(q *ent.UserQuery) { q.Select(user.FieldID) })

	res, err := q.Only(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoUser(res), nil
}
func (s *UserServiceServer) Update(ctx context.Context, req *horus.UpdateUserRequest) (*horus.User, error) {
	id, err := GetUserId(ctx, s.db, req.GetKey())
	if err != nil {
		return nil, err
	}

	q := s.db.User.UpdateOneID(id)
	if v := req.Alias; v != nil {
		q.SetAlias(*v)
	}
	if v := req.Parent; v != nil {
		if id, err := GetUserId(ctx, s.db, req.Parent); err != nil {
			return nil, err
		} else {
			q.SetParentID(id)
		}
	}

	res, err := q.Save(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoUser(res), nil
}
func ToProtoUser(v *ent.User) *horus.User {
	m := &horus.User{}
	m.Id = v.ID[:]
	m.DateCreated = timestamppb.New(v.DateCreated)
	m.Alias = v.Alias
	if v := v.Edges.Parent; v != nil {
		m.Parent = ToProtoUser(v)
	}
	for _, v := range v.Edges.Identities {
		m.Identities = append(m.Identities, ToProtoIdentity(v))
	}
	for _, v := range v.Edges.Accounts {
		m.Accounts = append(m.Accounts, ToProtoAccount(v))
	}
	for _, v := range v.Edges.Children {
		m.Children = append(m.Children, ToProtoUser(v))
	}
	return m
}
func GetUserId(ctx context.Context, db *ent.Client, req *horus.GetUserRequest) (uuid.UUID, error) {
	var r uuid.UUID
	k := req.GetKey()
	if t, ok := k.(*horus.GetUserRequest_Id); ok {
		if v, err := uuid.FromBytes(t.Id); err != nil {
			return r, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	q := db.User.Query()
	switch t := k.(type) {
	case *horus.GetUserRequest_Alias:
		q.Where(user.AliasEQ(t.Alias))
	case nil:
		return r, status.Errorf(codes.InvalidArgument, "key not provided")
	default:
		return r, status.Errorf(codes.Unimplemented, "unknown type of key")
	}
	if v, err := q.OnlyID(ctx); err != nil {
		return r, ToStatus(err)
	} else {
		return v, nil
	}
}
func GetUserSpecifier(req *horus.GetUserRequest) (predicate.User, error) {
	switch t := req.GetKey().(type) {
	case *horus.GetUserRequest_Id:
		if v, err := uuid.FromBytes(t.Id); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return user.IDEQ(v), nil
		}
	case *horus.GetUserRequest_Alias:
		return user.AliasEQ(t.Alias), nil
	case nil:
		return nil, status.Errorf(codes.InvalidArgument, "key not provided")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key")
	}
}
