// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"khepri.dev/horus/ent/account"
	"khepri.dev/horus/ent/invitation"
	"khepri.dev/horus/ent/silo"
)

// Invitation is the model entity for the Invitation schema.
type Invitation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Invitee holds the value of the "invitee" field.
	Invitee string `json:"invitee,omitempty"`
	// CreatedDate holds the value of the "created_date" field.
	CreatedDate time.Time `json:"created_date,omitempty"`
	// ExpiredDate holds the value of the "expired_date" field.
	ExpiredDate *time.Time `json:"expired_date,omitempty"`
	// AcceptedDate holds the value of the "accepted_date" field.
	AcceptedDate *time.Time `json:"accepted_date,omitempty"`
	// DeclinedDate holds the value of the "declined_date" field.
	DeclinedDate *time.Time `json:"declined_date,omitempty"`
	// CanceledDate holds the value of the "canceled_date" field.
	CanceledDate *time.Time `json:"canceled_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvitationQuery when eager-loading is set.
	Edges               InvitationEdges `json:"edges"`
	account_invitations *uuid.UUID
	silo_invitations    *uuid.UUID
	selectValues        sql.SelectValues
}

// InvitationEdges holds the relations/edges for other nodes in the graph.
type InvitationEdges struct {
	// Silo holds the value of the silo edge.
	Silo *Silo `json:"silo,omitempty"`
	// Inviter holds the value of the inviter edge.
	Inviter *Account `json:"inviter,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SiloOrErr returns the Silo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationEdges) SiloOrErr() (*Silo, error) {
	if e.loadedTypes[0] {
		if e.Silo == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: silo.Label}
		}
		return e.Silo, nil
	}
	return nil, &NotLoadedError{edge: "silo"}
}

// InviterOrErr returns the Inviter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationEdges) InviterOrErr() (*Account, error) {
	if e.loadedTypes[1] {
		if e.Inviter == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: account.Label}
		}
		return e.Inviter, nil
	}
	return nil, &NotLoadedError{edge: "inviter"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invitation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitation.FieldInvitee:
			values[i] = new(sql.NullString)
		case invitation.FieldCreatedDate, invitation.FieldExpiredDate, invitation.FieldAcceptedDate, invitation.FieldDeclinedDate, invitation.FieldCanceledDate:
			values[i] = new(sql.NullTime)
		case invitation.FieldID:
			values[i] = new(uuid.UUID)
		case invitation.ForeignKeys[0]: // account_invitations
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case invitation.ForeignKeys[1]: // silo_invitations
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invitation fields.
func (i *Invitation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case invitation.FieldID:
			if value, ok := values[j].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[j])
			} else if value != nil {
				i.ID = *value
			}
		case invitation.FieldInvitee:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invitee", values[j])
			} else if value.Valid {
				i.Invitee = value.String
			}
		case invitation.FieldCreatedDate:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_date", values[j])
			} else if value.Valid {
				i.CreatedDate = value.Time
			}
		case invitation.FieldExpiredDate:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_date", values[j])
			} else if value.Valid {
				i.ExpiredDate = new(time.Time)
				*i.ExpiredDate = value.Time
			}
		case invitation.FieldAcceptedDate:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_date", values[j])
			} else if value.Valid {
				i.AcceptedDate = new(time.Time)
				*i.AcceptedDate = value.Time
			}
		case invitation.FieldDeclinedDate:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field declined_date", values[j])
			} else if value.Valid {
				i.DeclinedDate = new(time.Time)
				*i.DeclinedDate = value.Time
			}
		case invitation.FieldCanceledDate:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field canceled_date", values[j])
			} else if value.Valid {
				i.CanceledDate = new(time.Time)
				*i.CanceledDate = value.Time
			}
		case invitation.ForeignKeys[0]:
			if value, ok := values[j].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field account_invitations", values[j])
			} else if value.Valid {
				i.account_invitations = new(uuid.UUID)
				*i.account_invitations = *value.S.(*uuid.UUID)
			}
		case invitation.ForeignKeys[1]:
			if value, ok := values[j].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field silo_invitations", values[j])
			} else if value.Valid {
				i.silo_invitations = new(uuid.UUID)
				*i.silo_invitations = *value.S.(*uuid.UUID)
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invitation.
// This includes values selected through modifiers, order, etc.
func (i *Invitation) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// QuerySilo queries the "silo" edge of the Invitation entity.
func (i *Invitation) QuerySilo() *SiloQuery {
	return NewInvitationClient(i.config).QuerySilo(i)
}

// QueryInviter queries the "inviter" edge of the Invitation entity.
func (i *Invitation) QueryInviter() *AccountQuery {
	return NewInvitationClient(i.config).QueryInviter(i)
}

// Update returns a builder for updating this Invitation.
// Note that you need to call Invitation.Unwrap() before calling this method if this Invitation
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Invitation) Update() *InvitationUpdateOne {
	return NewInvitationClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Invitation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Invitation) Unwrap() *Invitation {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Invitation is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Invitation) String() string {
	var builder strings.Builder
	builder.WriteString("Invitation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("invitee=")
	builder.WriteString(i.Invitee)
	builder.WriteString(", ")
	builder.WriteString("created_date=")
	builder.WriteString(i.CreatedDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := i.ExpiredDate; v != nil {
		builder.WriteString("expired_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := i.AcceptedDate; v != nil {
		builder.WriteString("accepted_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := i.DeclinedDate; v != nil {
		builder.WriteString("declined_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := i.CanceledDate; v != nil {
		builder.WriteString("canceled_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Invitations is a parsable slice of Invitation.
type Invitations []*Invitation
