// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authorizer is the predicate function for authorizer builders.
type Authorizer func(*sql.Selector)

// Identity is the predicate function for identity builders.
type Identity func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
