//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Horus_Status_FullMethodName = "/khepri.horus.Horus/Status"
)

// HorusClient is the client API for Horus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HorusClient interface {
	Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusRes, error)
}

type horusClient struct {
	cc grpc.ClientConnInterface
}

func NewHorusClient(cc grpc.ClientConnInterface) HorusClient {
	return &horusClient{cc}
}

func (c *horusClient) Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusRes, error) {
	out := new(StatusRes)
	err := c.cc.Invoke(ctx, Horus_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HorusServer is the server API for Horus service.
// All implementations must embed UnimplementedHorusServer
// for forward compatibility
type HorusServer interface {
	Status(context.Context, *StatusReq) (*StatusRes, error)
	mustEmbedUnimplementedHorusServer()
}

// UnimplementedHorusServer must be embedded to have forward compatible implementations.
type UnimplementedHorusServer struct {
}

func (UnimplementedHorusServer) Status(context.Context, *StatusReq) (*StatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedHorusServer) mustEmbedUnimplementedHorusServer() {}

// UnsafeHorusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HorusServer will
// result in compilation errors.
type UnsafeHorusServer interface {
	mustEmbedUnimplementedHorusServer()
}

func RegisterHorusServer(s grpc.ServiceRegistrar, srv HorusServer) {
	s.RegisterService(&Horus_ServiceDesc, srv)
}

func _Horus_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HorusServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Horus_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HorusServer).Status(ctx, req.(*StatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Horus_ServiceDesc is the grpc.ServiceDesc for Horus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Horus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "khepri.horus.Horus",
	HandlerType: (*HorusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Horus_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
